import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import BootstrapClient from "./components/bootstrapClient";
import { SessionProvider } from "next-auth/react";
import "../app/globals.css";
import components from "./components";

export const metadata = {
  title: "La StAtion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <SessionProvider>
          <BootstrapClient />
          <components.Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
